# Copyright 2025 Cisco Systems, Inc. and its affiliates
#
# SPDX-License-Identifier: Apache-2.0

---
name: "Unit Test Python"

on:
  push:
  workflow_dispatch:

# Declare default permissions as read-only
permissions: read-all

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: ${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }} @ ${{ ((github.ref_name == 'main') && github.run_id) || ''}}
  cancel-in-progress: ${{ !( github.ref_name == 'main') }}

jobs:
  unit-tests:
    runs-on: ubuntu-22.04-x86_64-large
    permissions:
      contents: read
    steps:
      # Check out with entire commit history to ensure all commits and tags
      # are available for correct versioning.
      - name: ðŸ“¦ checkout repository
        uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: "Setup Python"
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: "Setup venv"
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -U pip
          pip install -e '.[test]'

      - name: "Run tests"
        run: |
          source .venv/bin/activate
          make test_all
